# fly.toml
app = 'mysql-deploys'
primary_region = 'nrt'

[http_service]
  internal_port = 3306
  force_https = false
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  internal_port = 3306
  protocol = "tcp"
  
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 3306

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[build]
  image = "mysql:8.0"

[env]
  MYSQL_ROOT_PASSWORD = "rootwhdudwo0824!@"  # 루트 비밀번호 설정
  MYSQL_ROOT_HOST = "%"                      # 외부 IP에서 접속 허용
