server.port=${PORT:8080}

spring.cache.type=simple
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=6h

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

youtube.api.key=${youtube.api.key}

# chzzk API
chzzk.client.id=${chzzk.client.id}
chzzk.client.secret=${chzzk.client.secret}
chzzk.nid.aut=${chzzk.nid.aut}
chzzk.nid.ses=${chzzk.nid.ses}